### ISSUE TITLE
SyntaxError: Unexpected token '.'  at wrapSafe (internal/modules/cjs/loader.js:915:16) ...

### ISSUE THREAD

**Issue by BarfingLemurs** [aseichter2007/ClipboardConqueror#6]
```
linux@changeme:~/projects/ClipboardConqueror$ ./y-linux-mac-install.sh 

added 54 packages, and audited 55 packages in 9s

5 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
linux@changeme:~/projects/ClipboardConqueror$ ls
CCfinal.jpg         node_modules               updateCC.bat
Examples.txt        package-lock.json          y-linux-mac-install.sh
LICENSE             package.json               y-linux-mac-start-no-nodemon.sh
SettingsConqueror   readme.md                  y-linux-mac-start-nodemon.sh
WhatIsCC.md         responsengine.js           z-instalCC.bat
copyconqueror.js    sampleLaunchKoboldBat.bat  z-runCC.bat
hermes16.kcpps      settingSaver.js            z-runCCnodeMon.bat
icon.jpg            setup.js
koboldinterface.js  textengine.js
linux@changeme:~/projects/ClipboardConqueror$ ./y-linux-mac-start-no-nodemon.sh 
 
> clipboardconqueror@1.0.0 linuxnomon
> chmod +x node_modules/clipboard-event/platform/clipboard-event-handler-linux && node copyconqueror.js

/home/linux/projects/ClipboardConqueror/node_modules/copy-paste/index.js:58
	if(text?.pipe) { text.pipe(child.stdin); }
	        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/linux/projects/ClipboardConqueror/copyconqueror.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
linux@changeme:~/projects/ClipboardConqueror$ ./y-linux-mac-start-nodemon.sh 

> clipboardconqueror@1.0.0 linux
> chmod +x node_modules/clipboard-event/platform/clipboard-event-handler-linux && nodemon copyconqueror.js

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node copyconqueror.js`
/home/linux/projects/ClipboardConqueror/node_modules/copy-paste/index.js:58
	if(text?.pipe) { text.pipe(child.stdin); }
	        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/linux/projects/ClipboardConqueror/copyconqueror.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[nodemon] app crashed - waiting for file changes before starting...
```

OS: ubuntu 22.04
Pleatform: arm64

**Comment by aseichter2007** [comment]
I just saw this, did you get it sorted out?  That looks like a problem in the node copy-paste library. Do you have any more details so I might chase it down?

**Comment by BarfingLemurs** [comment]
sorry, I just assumed that nodejs packages wont work or arent installing properly on my hardware so it could be my fault, and when I tried a different project (e.g. "SillyTavern") I ran into additional issues.

That said, those issues seemed  to resolve themselves when I ran their ./start.sh, which took care of installing nodejs and npm somehow for me.

**Comment by aseichter2007** [comment]
If you have node now, CC should work for you.
